version: "3.7"
services:
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
  food-it-server:
    image: foodbank-it-server
    restart: on-failure
    depends_on:
      - mysql-server
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=mysql-server
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=banque_alimentaire
      - DATABASE_PORT=3306
  food-it-client:
    image: foodbank-it-client
    restart: on-failure
    depends_on:
      - food-it-server
    ports:
      - 80:80
    environment:
      - apiUrl='http://food-it-server:8081/api/'
          
volumes:
  mysql-data:
